### ISSUE TITLE
Getting an Error in Advanced ASP.Net Core 3 after installing your NuGet package..  

### ISSUE THREAD

**Issue by jontiefer** [KevinDockx/HttpCacheHeaders#85]
I've been following your Implementing Advanced Restful Concerns ASP.Net Core 3 course step by step , so I was stumped after installing the latest version of this to see this error message has been thrown.  I cannot figure out what is wrong. I  will try installing version 4 and see if that helps the error go away.  If I can figure out what is going on before you respond, I will update you on what happened.

**Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Marvin.Cache.Headers.IStoreKeyAccessor Lifetime: Transient ImplementationType: Marvin.Cache.Headers.StoreKeyAccessor': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Marvin.Cache.Headers.StoreKeyAccessor'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Marvin.Cache.Headers.IStoreKeyAccessor Lifetime: Transient ImplementationType: Marvin.Cache.Headers.StoreKeyAccessor': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Marvin.Cache.Headers.StoreKeyAccessor'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Marvin.Cache.Headers.StoreKeyAccessor'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CourseLibrary.API.Program.Main(String[] args) in C:\Test\Dockx ASP.NET Core\CourseLibrary.API\CourseLibrary.API\Program.cs:line 16**

**Comment by jontiefer** [comment]
I installed version 4.0 of your package and same problem. I do have the latest version of ASP.Net Core on my comptuer. Maye there is some conflict with the library and the latest .Net core version?  Banging my head here.

**Comment by jontiefer** [comment]
I took your project that is ASP.Net Core 3.0 and used it instead of mine that was compiled in ASP.Net Core 3.1 and it does run. I  will try to finish off the course using your sample code which for seem reason that boggles my brain actually compiles with your library.  I have no clue why as our code matches and maybe it is some corruption in my project or some mismatch of one library version since I am using the newest libraries for everything in the project.  I will try to tinker with it a bit and see what happens when I install newer libraries.  I did have my project file configured for dotnet watch run  so I can more quickly launch my code, but that;'s the only difference.  I even copied and pasted your finished Startup.cs and Program. cs and made no difference for it throwing errors in my code.   I am definitely scratching my head on this one.

**Comment by KevinDockx** [comment]
Hello @jontiefer ,

In the error I see that the Microsoft.AspNetCore.Http.IHttpContextAccessor service couldn't be resolved - could it be that you haven't registered that on the IServiceCollection?  

Going to mark this as a feature request: I can ensure that the cache middleware will register its own dependencies in case they haven't been registered yet :)

**Comment by jontiefer** [comment]
Hi @KevinDockx .. 

Sorry , I finished your course a few days ago and now onto a Linux course and didn't have time to respond to you.  I don't believe I did anything wrong at all. In fact, I took your Start sample code of module 8 and then just went step by step in your example and it threw the same error as in my own code project I was working on throughout the course.   I believe I registered everything in Startup that you instructed in your video and attempted multiple times.   

The only way I could get your library to compile was taking the End sample code of that module 8 and then it literally worked.  I ended up going through your module 8 step by step and commenting out and following the course as good as I could with the finished module code.  I was able to replicate each line in the module 8 course and it compiled and worked successfully.

I am very stumped as to why it didn't compile and after hours of banging my head against the table I kind of just gave up and used the module 8 End code for throughout the rest of the course.

I would ask if you could take the Start code from Module 8 of your asp-dot-net-core-3-advanced-restful-concerns that you have provided us in the course, then go step by step in your course on Module 8 and see if you could reproduce the same problem that I did. 

If nothing happens for you, then maybe it is some glitch with my Windows 10 Pro OS , .Net Framework or some other weird and bizarre problem I cannot figure out.  But I did get it to work fine with the End demo code from Module 8. 

I hope that provides you more information.

**Comment by KevinDockx** [comment]
Hi Jonathan,

thanks a lot, this will really help in pinpointing the issue.

**Comment by KevinDockx** [comment]
Fixed with #3aebaf8

**Comment by KevinDockx** [comment]
Released: https://www.nuget.org/packages/Marvin.Cache.Headers/5.0.1
